# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d521e8eb0e3975242e98387876e112139e1f4a059dfa27ab877b23de162b1d46e47650a4d40fd3b55383eae0e5ecf96690094e70d31dea0a18b7056f3ace3d9

test:
  secret_key_base: 2d19e6d2ca3605e8030c393ee962e176bce9960cfa6b5d05ff72e938ead02609ef00ea39a027dac28a60c02d0f02cbb9eceb4b685e18c048048d4e0be1fa5254

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
